SolidarnieWebApp/Controllers/ZamowieniaController.cs
using System.Web.Mvc;
using Kruchy.Core.Autentykacja;
using Kruchy.Core.Mapowanie;
using Kruchy.Uzytkownicy.Uprawnienia;
using Kruchy.Zakupy.Services;
using SolidarnieWebApp.Extensions;
using SolidarnieWebApp.Models;

namespace SolidarnieWebApp.Controllers
{
    public class ZamowieniaController : Controller
    {
        private readonly IDefinicjeZamowieniaService definicjeService;
        private readonly ISumowanieZamowieniaService sumowanieService;
        private readonly IUzytkownikProvider uzytkownikProvider;
        private readonly IUprawnieniaService uprawnieniaService;

        public ZamowieniaController(
            IDefinicjeZamowieniaService definicjeService,
            ISumowanieZamowieniaService sumowanieService,
            IUzytkownikProvider uzytkownikProvider,
            IUprawnieniaService uprawnieniaService)
        {
            this.definicjeService = definicjeService;
            this.sumowanieService = sumowanieService;
            this.uzytkownikProvider = uzytkownikProvider;
            this.uprawnieniaService = uprawnieniaService;
        }

        public ActionResult Index()
        {
            var model = new ListaDefinicjiZamowieniaModel(
                definicjeService.SzukajWszystkich());
            uprawnieniaService.UstawCzyAdministrator(
                uzytkownikProvider,
                o => model.Administrator = o);

            ViewBag.Administrator = model.Administrator;

            return View(model);
        }

        public ActionResult Sumuj(int definicjaID)
        {
            var zsumowaneZamowienie = sumowanieService.Sumuj(definicjaID);
            var model = zsumowaneZamowienie.Mapuj<ZsumowaneZamowienieModel>();
            return View(model);
        }
    }
}

SolidarnieWebApp/Controllers/ZamowienieFormController.cs
using System;
using System.IO;
using System.Web.Mvc;
using Kruchy.Zakupy.Services;
using SolidarnieWebApp.Authentication;
using SolidarnieWebApp.Models;
using SolidarnieWebApp.Walidacja;

namespace SolidarnieWebApp.Controllers
{
    [WymagaLogowania]
    public class ZamowienieFormController : Controller
    {
        private readonly IDefinicjeZamowieniaService definicjeService;

        public ZamowienieFormController(
            IDefinicjeZamowieniaService definicjeService)
        {
            this.definicjeService = definicjeService;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new ZamowienieModel());
        }

        [HttpPost]
        public ActionResult Create(ZamowienieModel form)
        {
            var listenerWalidacji = this.DajListeneraWalidacji();
            var wynikWstawienia =
                definicjeService.Wstaw(DajRequestWstawienia(form), listenerWalidacji);
            if (wynikWstawienia.HasValue)
            {
                return RedirectToAction("Index", "Zamowienia");
            }
            return View(form);
        }

        private WstawienieDefinicjiZamowieniaRequest DajRequestWstawienia(
            ZamowienieModel form)
        {
            return new WstawienieDefinicjiZamowieniaRequest
            {
                DataKoncaZamawiania = form.CzasKoncaZamawiania,
                Nazwa = form.Nazwa,
                NazwaPliku = form?.Plik?.FileName,
                ZawartoscPliku = DajZawartoscPliku(form?.Plik?.InputStream)
            };
        }

        private byte[] DajZawartoscPliku(Stream inputStream)
        {
            if (inputStream == null)
                return null;

            using (var ms = new MemoryStream())
            {
                inputStream.CopyTo(ms);
                return ms.ToArray();
            }
        }
    }
}

SolidarnieWebApp/Views/Zamowienia/IlosciUzytkownikow.cshtml
@using Kruchy.Zakupy.Views;
@model KomorkaTabeliModel

@{ 
    var wiersz = (ZamowionyProduktModel)Model.Wiersz;
    var ilosciUzytkownika = wiersz.IlosciUzytkownikow as IEnumerable<IloscUzytkownika>;
}
<ul>
@foreach (var iloscUzytkownika in ilosciUzytkownika)
{
    <li>@iloscUzytkownika.NazwaUzytkownika - @iloscUzytkownika.Ilosc</li>
}
</ul>

SolidarnieWebApp/Views/Zamowienia/KolumnaAkcji.cshtml
@{
    bool administrator = ViewBag.Administrator;
}
@if (administrator)
{
    <a href="@Url.Action("Edit", "ZamowienieForm", new { id = Model.Wiersz.ID })" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-edit"></span>
        Edytuj
    </a>
}
<a href="@Url.Action("Index", "ZamowienieUzytkownika", new { definicjaID = Model.Wiersz.ID })" class="btn btn-default btn-sm">
    Zamów
</a>
<a href="@Url.Action("Sumuj", new { definicjaID = Model.Wiersz.ID })" class="btn btn-default btn-sm">
    <span class="glyphicon glyphicon-stats"></span>
    Sumuj
</a> 